"""Build versioned object store tests"""
import daos_build

def scons():
    """Execute build"""
    Import('denv', 'prereqs', 'utest_utils')

    pmemobj_libs = ['pthread', 'pmemobj']
    libraries = ['vos', 'bio', 'abt', 'pthread', 'daos_common', 'daos_tests',
                 'gurt', 'cart', 'uuid', 'cmocka', 'gomp']
    libraries.append(pmemobj_libs)

    prereqs.require(denv, 'argobots')

    # Add runtime paths for daos libraries
    denv.AppendUnique(RPATH=[Literal(r'\$$ORIGIN/../lib64/daos_srv')])

    vos_test_src = ['vos_tests.c', 'vts_io.c', 'vts_pool.c', 'vts_container.c',
                    denv.Object("vts_common.c"), 'vts_aggregate.c', 'vts_dtx.c',
                    'vts_gc.c', 'vts_checksum.c', 'vts_ilog.c',
                    'vts_array.c', 'vts_pm.c']
    vos_tests = daos_build.program(denv, 'vos_tests', vos_test_src,
                                   LIBS=libraries)
    denv.AppendUnique(CPPPATH=["../../common/tests"])
    evt_ctl = daos_build.program(denv, 'evt_ctl', ['evt_ctl.c', utest_utils],
                                 LIBS=libraries)
    pmemobj_mt_safety = daos_build.program(denv, 'pmemobj_mt_safety',
                                           'pmemobj_mt_safety.c',
                                            LIBS=pmemobj_libs)

    vos_size = daos_build.program(denv, 'vos_size', ['vos_size.c'],
                                  LIBS=libraries)

    denv.Install('$PREFIX/bin/', [vos_tests, vos_size, evt_ctl, 'vos_size.py'])
    denv.Install('$PREFIX/etc/', ['vos_size_input.yaml', 'vos_dfs_sample.yaml'])

if __name__ == "SCons.Script":
    scons()
